/**
 * FIT Sub-Sport Constants (camelCase - from Garmin SDK)
 * Reference: https://developer.garmin.com/fit/file-types/workout/
 */
export const FIT_SUB_SPORT = {
  GENERIC: "generic",
  TREADMILL: "treadmill",
  STREET: "street",
  TRAIL: "trail",
  TRACK: "track",
  SPIN: "spin",
  INDOOR_CYCLING: "indoorCycling",
  ROAD: "road",
  MOUNTAIN: "mountain",
  DOWNHILL: "downhill",
  RECUMBENT: "recumbent",
  CYCLOCROSS: "cyclocross",
  HAND_CYCLING: "handCycling",
  TRACK_CYCLING: "trackCycling",
  INDOOR_ROWING: "indoorRowing",
  ELLIPTICAL: "elliptical",
  STAIR_CLIMBING: "stairClimbing",
  LAP_SWIMMING: "lapSwimming",
  OPEN_WATER: "openWater",
  FLEXIBILITY_TRAINING: "flexibilityTraining",
  STRENGTH_TRAINING: "strengthTraining",
  WARM_UP: "warmUp",
  MATCH: "match",
  EXERCISE: "exercise",
  CHALLENGE: "challenge",
  INDOOR_SKIING: "indoorSkiing",
  CARDIO_TRAINING: "cardioTraining",
  INDOOR_WALKING: "indoorWalking",
  E_BIKE_FITNESS: "eBikeFitness",
  BMX: "bmx",
  CASUAL_WALKING: "casualWalking",
  SPEED_WALKING: "speedWalking",
  BIKE_TO_RUN_TRANSITION: "bikeToRunTransition",
  RUN_TO_BIKE_TRANSITION: "runToBikeTransition",
  SWIM_TO_BIKE_TRANSITION: "swimToBikeTransition",
  ATV: "atv",
  MOTOCROSS: "motocross",
  BACKCOUNTRY: "backcountry",
  RESORT: "resort",
  RC_DRONE: "rcDrone",
  WINGSUIT: "wingsuit",
  WHITEWATER: "whitewater",
  SKATE_SKIING: "skateSkiing",
  YOGA: "yoga",
  PILATES: "pilates",
  INDOOR_RUNNING: "indoorRunning",
  GRAVEL_CYCLING: "gravelCycling",
  E_BIKE_MOUNTAIN: "eBikeMountain",
  COMMUTING: "commuting",
  MIXED_SURFACE: "mixedSurface",
  NAVIGATE: "navigate",
  TRACK_ME: "trackMe",
  MAP: "map",
  SINGLE_GAS_DIVING: "singleGasDiving",
  MULTI_GAS_DIVING: "multiGasDiving",
  GAUGE_DIVING: "gaugeDiving",
  APNEA_DIVING: "apneaDiving",
  APNEA_HUNTING: "apneaHunting",
  VIRTUAL_ACTIVITY: "virtualActivity",
  OBSTACLE: "obstacle",
  ALL: "all",
} as const;
