import js from "@eslint/js";
import boundaries from "eslint-plugin-boundaries";
import reactHooks from "eslint-plugin-react-hooks";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import tseslint from "typescript-eslint";
import vitest from "@vitest/eslint-plugin";

import noNarrativeComments from "./scripts/eslint-rules/no-narrative-comments.mjs";

const adapterPackages = ["fit", "tcx", "zwo", "garmin", "garmin-connect"];

// garmin-connect legitimately depends on garmin (GCN format)
const adapterAllowedDeps = {
  "garmin-connect": ["garmin"],
};

function adapterBoundaryRules() {
  return adapterPackages.map((pkg) => ({
    files: [`packages/${pkg}/src/**/*.ts`],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: adapterPackages
            .filter((other) => other !== pkg)
            .filter((other) => !(adapterAllowedDeps[pkg] ?? []).includes(other))
            .map((other) => ({
              name: `@kaiord/${other}`,
              message:
                "Adapter packages must not depend on other adapters. Depend on @kaiord/core only.",
            })),
        },
      ],
    },
  }));
}

/** Shared import sort + type import rules */
const importRules = {
  "simple-import-sort/imports": "error",
  "simple-import-sort/exports": "error",
  "@typescript-eslint/consistent-type-imports": [
    "error",
    {
      prefer: "type-imports",
      fixStyle: "separate-type-imports",
    },
  ],
};

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    ignores: [
      "**/dist/**",
      "**/coverage/**",
      "**/node_modules/**",
      "**/*.config.js",
      "**/*.config.ts",
      "**/scripts/**",
      // Test files are NOT globally ignored anymore — they fall
      // through to the test-files override block at lines ~145+
      // which applies relaxed test-specific rules + the vitest
      // plugin's `valid-title` rule (test-conventions-should-aaa
      // change PR-1 §1.2). Storybook stories remain ignored.
      "**/*.stories.ts",
      "**/*.stories.tsx",
      "**/playwright-report/**",
      "**/test-results/**",
      "**/.playwright/**",
      "**/.storybook/**",
      "**/storybook-static/**",
      "**/test-setup.ts",
      "**/test-utils/**",
      // Generated SDK-sourced model catalog — regenerated by
      // `pnpm generate:model-catalog`; not hand-edited, so not linted.
      "**/generated/**",
    ],
  },
  {
    // Core package: strict 40 lines per function
    files: ["packages/core/**/*.ts", "packages/core/**/*.tsx"],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      "simple-import-sort": simpleImportSort,
    },
    rules: {
      "max-lines": [
        "error",
        { max: 100, skipBlankLines: true, skipComments: true },
      ],
      "max-lines-per-function": [
        "error",
        { max: 40, skipBlankLines: true, skipComments: true },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      ...importRules,
    },
  },
  {
    // Backend adapter packages: same rules as core
    files: [
      "packages/fit/**/*.ts",
      "packages/tcx/**/*.ts",
      "packages/zwo/**/*.ts",
      "packages/garmin/**/*.ts",
      "packages/garmin-connect/**/*.ts",
      "packages/cli/**/*.ts",
      "packages/mcp/**/*.ts",
    ],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      "simple-import-sort": simpleImportSort,
    },
    rules: {
      "max-lines": [
        "error",
        { max: 100, skipBlankLines: true, skipComments: true },
      ],
      "max-lines-per-function": [
        "error",
        { max: 40, skipBlankLines: true, skipComments: true },
      ],
      complexity: ["error", 10],
      "max-depth": ["error", 4],
      "max-params": ["error", 4],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      ...importRules,
    },
  },
  {
    // Frontend package: relaxed 60 lines per function for React components
    files: [
      "packages/workout-spa-editor/**/*.ts",
      "packages/workout-spa-editor/**/*.tsx",
    ],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      "simple-import-sort": simpleImportSort,
      "react-hooks": reactHooks,
    },
    rules: {
      "max-lines": [
        "error",
        { max: 80, skipBlankLines: true, skipComments: true },
      ],
      "max-lines-per-function": [
        "error",
        { max: 60, skipBlankLines: true, skipComments: true },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "error",
      ...importRules,
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@kaiord/fit",
              message: "Use dynamic import() for code splitting.",
              allowTypeImports: true,
            },
            {
              name: "@kaiord/tcx",
              message: "Use dynamic import() for code splitting.",
              allowTypeImports: true,
            },
            {
              name: "@kaiord/zwo",
              message: "Use dynamic import() for code splitting.",
              allowTypeImports: true,
            },
            {
              name: "@kaiord/garmin",
              message: "Use dynamic import() for code splitting.",
              allowTypeImports: true,
            },
          ],
        },
      ],
    },
  },
  {
    // Playwright e2e fixtures: the `use` parameter is the Playwright
    // fixture API, not a React hook. Disable react-hooks/* in e2e/.
    files: ["packages/workout-spa-editor/e2e/**/*.ts"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
      "react-hooks/exhaustive-deps": "off",
    },
  },
  {
    // All SPA logging goes through src/utils/logger.ts so log levels and
    // transports stay controllable. Only the logger itself, the
    // console-spy test utilities, and tests may touch console directly.
    files: [
      "packages/workout-spa-editor/src/**/*.ts",
      "packages/workout-spa-editor/src/**/*.tsx",
    ],
    ignores: [
      "packages/workout-spa-editor/src/utils/logger.ts",
      "packages/workout-spa-editor/src/test-utils/**",
      "packages/workout-spa-editor/src/**/*.test.ts",
      "packages/workout-spa-editor/src/**/*.test.tsx",
      "packages/workout-spa-editor/src/**/*.stories.ts",
      "packages/workout-spa-editor/src/**/*.stories.tsx",
    ],
    rules: {
      "no-console": "error",
    },
  },
  {
    // Coaching dialog files MUST NOT consume the coaching-source registry
    // directly (Rules-of-Hooks compliance + single source materialization).
    // The dialog receives `expandActivity` as a callback prop instead.
    files: [
      "packages/workout-spa-editor/src/components/molecules/CoachingCard/CoachingActivityDialog.tsx",
      "packages/workout-spa-editor/src/components/molecules/CoachingCard/CoachingActivityDialogContent.tsx",
      "packages/workout-spa-editor/src/components/molecules/CoachingCard/use-coaching-dialog.ts",
    ],
    plugins: {
      "@typescript-eslint": tseslint.plugin,
    },
    rules: {
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "**/contexts/coaching-registry-context",
                "**/contexts/coaching-registry-context.*",
                "@/contexts/coaching-registry-context",
                "@/contexts/coaching-registry-context.*",
                "**/types/coaching-source",
                "**/types/coaching-source.*",
                "@/types/coaching-source",
                "@/types/coaching-source.*",
              ],
              message:
                "Coaching dialog must not consume the registry directly; receive `expandActivity` as a prop. Import `CoachingActivity` from `coaching-activity` instead.",
            },
          ],
        },
      ],
    },
  },
  {
    // Frontend page components: allow more lines for orchestration
    files: ["packages/workout-spa-editor/**/pages/**/*.tsx"],
    rules: {
      "max-lines": [
        "error",
        { max: 150, skipBlankLines: true, skipComments: true },
      ],
    },
  },
  {
    // Public API entry points: disable max-lines
    files: ["**/src/index.ts", "**/index.ts"],
    rules: {
      "max-lines": "off",
    },
  },
  {
    // Hexagonal architecture boundaries for core package
    files: ["packages/core/src/**/*.ts"],
    plugins: { boundaries },
    settings: {
      "boundaries/elements": [
        { type: "domain", pattern: "packages/core/src/domain/**" },
        { type: "application", pattern: "packages/core/src/application/**" },
        { type: "ports", pattern: "packages/core/src/ports/**" },
        { type: "adapters", pattern: "packages/core/src/adapters/**" },
      ],
    },
    rules: {
      "boundaries/element-types": [
        "error",
        {
          default: "allow",
          rules: [
            {
              from: "domain",
              disallow: ["application", "ports", "adapters"],
              message:
                "Domain layer must not depend on {{target}}. Domain is pure and self-contained.",
            },
            {
              from: "application",
              disallow: ["adapters"],
              message:
                "Application layer must not depend on adapters. Use ports instead.",
            },
            {
              from: "ports",
              disallow: ["application", "adapters"],
              message:
                "Ports must not depend on {{target}}. Ports define interfaces only.",
            },
          ],
        },
      ],
    },
  },
  {
    // SPA hexagonal layering: ports / application / adapters / hooks /
    // components. Matches the convention used by @kaiord/core. Files in
    // a higher layer must not bypass the layer below them.
    files: ["packages/workout-spa-editor/src/**/*.{ts,tsx}"],
    plugins: { boundaries },
    settings: {
      "boundaries/elements": [
        {
          type: "spa-ports",
          pattern: "packages/workout-spa-editor/src/ports/**",
        },
        {
          type: "spa-application",
          pattern: "packages/workout-spa-editor/src/application/**",
        },
        {
          type: "spa-adapters",
          pattern: "packages/workout-spa-editor/src/adapters/**",
        },
        {
          type: "spa-hooks",
          pattern: "packages/workout-spa-editor/src/hooks/**",
        },
        {
          type: "spa-components",
          pattern: "packages/workout-spa-editor/src/components/**",
        },
      ],
    },
    rules: {
      "boundaries/element-types": [
        "error",
        {
          default: "allow",
          rules: [
            {
              from: "spa-ports",
              disallow: ["spa-adapters"],
              message:
                "Ports must not depend on adapters. Ports define interfaces only.",
            },
            {
              from: "spa-application",
              disallow: ["spa-adapters"],
              message:
                "Application use cases must not depend on adapters. Inject through ports instead.",
            },
            {
              from: "spa-components",
              disallow: ["spa-adapters"],
              message:
                "Components must not import from adapters directly. Go through hooks (which compose use cases with injected ports).",
            },
          ],
        },
      ],
      "no-restricted-syntax": [
        "error",
        {
          // MatchSuggestion type lives in src/application/match-suggestion.ts.
          // Redeclaring elsewhere bypasses the single-source-of-truth contract
          // between the auto-match heuristic (producer) and the banner UI
          // (consumer). The canonical file is exempted in the override below.
          selector: "TSTypeAliasDeclaration[id.name='MatchSuggestion']",
          message:
            "MatchSuggestion is owned by application/match-suggestion.ts. Import it from there instead of redeclaring.",
        },
        {
          selector: "TSInterfaceDeclaration[id.name='MatchSuggestion']",
          message:
            "MatchSuggestion is owned by application/match-suggestion.ts. Import it from there instead of redeclaring.",
        },
      ],
    },
  },
  {
    // Canonical owner of MatchSuggestion — re-enable the type alias
    // declaration that the no-restricted-syntax rule above forbids
    // everywhere else.
    files: ["packages/workout-spa-editor/src/application/match-suggestion.ts"],
    rules: {
      "no-restricted-syntax": "off",
    },
  },
  ...adapterBoundaryRules(),
  {
    // Test files: relaxed test-specific rules + the vitest plugin's
    // `valid-title` rule (test-conventions-should-aaa change PR-1).
    //
    // Placed AFTER every production-code block so that, in flat-config
    // cascade order, this block's relaxations win for any *.test.{ts,tsx}
    // / *.spec.ts file that ALSO matched a stricter production block
    // (the SPA `*.tsx` block, the pages block, the core/backend blocks).
    // Tests are still linted by the production blocks above — only the
    // rules listed here are overridden.
    files: [
      "**/*.test.ts",
      "**/*.test.tsx",
      "**/*.spec.ts",
      "**/tests/**/*.{ts,tsx}",
    ],
    languageOptions: {
      parser: tseslint.parser,
      // Test files are not in the package tsconfig's `include`, so
      // `projectService: true` (inherited from earlier blocks) produces
      // "file not found by project service" parse errors. Disable
      // type-aware parsing for tests.
      parserOptions: {
        projectService: false,
        project: null,
      },
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      "simple-import-sort": simpleImportSort,
      vitest,
    },
    rules: {
      // Production-code structural limits don't apply to tests:
      // describe/it bodies are naturally branchy and longer than
      // production functions. Same precedent the original test-files
      // block established for max-lines/max-lines-per-function.
      "max-lines": "off",
      "max-lines-per-function": "off",
      complexity: "off",
      "max-depth": "off",
      "max-params": "off",
      "no-magic-numbers": [
        "warn",
        {
          ignore: [0, 1, 2, -1, 100, 200, 400, 404, 500],
          ignoreArrayIndexes: true,
          ignoreDefaultValues: true,
          enforceConst: true,
          detectObjects: false,
        },
      ],
      // test-conventions: every it()/it.alias()/it.each([])() title
      // SHALL start with "should " (case-sensitive lowercase). Locked
      // at 'error' after the title-allowlist drained to empty.
      "vitest/valid-title": [
        "error",
        {
          mustMatch: { it: ["^should "] },
        },
      ],
    },
  },
  {
    // Local rule: ban narrative / history-telling comments across
    // production code. The rule's pattern table is corpus-calibrated
    // against `main`; see `.omc/specs/deep-dive-cleanup-narrative-comments.md`
    // and `.omc/plans/ralplan-no-narrative-comments.md`.
    files: ["packages/**/*.{ts,tsx}"],
    plugins: {
      local: { rules: { "no-narrative-comments": noNarrativeComments } },
    },
    rules: { "local/no-narrative-comments": "error" },
  },
  {
    // Held-out path: Dexie migration adapters document the immutable
    // forward-only migration contract (`// v8 —` changelog, legacy
    // row markers). The rule is disabled here per spec §AC-3.
    files: ["packages/workout-spa-editor/src/adapters/dexie/**"],
    rules: { "local/no-narrative-comments": "off" },
  }
);
