import type { Sport } from "@kaiord/core";

import type { FitSport } from "../schemas/fit-sport";

/**
 * Bidirectional anchor: FIT `Sport` is camelCase, KRD `sport` is snake_case.
 * Both enums share the same order, so each entry pairs index-by-index.
 */
export const FIT_TO_KRD_SPORT: Record<FitSport, Sport> = {
  generic: "generic",
  running: "running",
  cycling: "cycling",
  transition: "transition",
  fitnessEquipment: "fitness_equipment",
  swimming: "swimming",
  basketball: "basketball",
  soccer: "soccer",
  tennis: "tennis",
  americanFootball: "american_football",
  training: "training",
  walking: "walking",
  crossCountrySkiing: "cross_country_skiing",
  alpineSkiing: "alpine_skiing",
  snowboarding: "snowboarding",
  rowing: "rowing",
  mountaineering: "mountaineering",
  hiking: "hiking",
  multisport: "multisport",
  paddling: "paddling",
  flying: "flying",
  eBiking: "e_biking",
  motorcycling: "motorcycling",
  boating: "boating",
  driving: "driving",
  golf: "golf",
  hangGliding: "hang_gliding",
  horsebackRiding: "horseback_riding",
  hunting: "hunting",
  fishing: "fishing",
  inlineSkating: "inline_skating",
  rockClimbing: "rock_climbing",
  sailing: "sailing",
  iceSkating: "ice_skating",
  skyDiving: "sky_diving",
  snowshoeing: "snowshoeing",
  snowmobiling: "snowmobiling",
  standUpPaddleboarding: "stand_up_paddleboarding",
  surfing: "surfing",
  wakeboarding: "wakeboarding",
  waterSkiing: "water_skiing",
  kayaking: "kayaking",
  rafting: "rafting",
  windsurfing: "windsurfing",
  kitesurfing: "kitesurfing",
  tactical: "tactical",
  jumpmaster: "jumpmaster",
  boxing: "boxing",
  floorClimbing: "floor_climbing",
  baseball: "baseball",
  diving: "diving",
  shooting: "shooting",
  winterSport: "winter_sport",
  grinding: "grinding",
  hiit: "hiit",
  videoGaming: "video_gaming",
  racket: "racket",
  wheelchairPushWalk: "wheelchair_push_walk",
  wheelchairPushRun: "wheelchair_push_run",
  meditation: "meditation",
  paraSport: "para_sport",
  discGolf: "disc_golf",
  teamSport: "team_sport",
  cricket: "cricket",
  rugby: "rugby",
  hockey: "hockey",
  lacrosse: "lacrosse",
  volleyball: "volleyball",
  waterTubing: "water_tubing",
  wakesurfing: "wakesurfing",
  waterSport: "water_sport",
  archery: "archery",
  mixedMartialArts: "mixed_martial_arts",
  motorSports: "motor_sports",
  snorkeling: "snorkeling",
  dance: "dance",
  jumpRope: "jump_rope",
  poolApnea: "pool_apnea",
  mobility: "mobility",
  geocaching: "geocaching",
  canoeing: "canoeing",
};
