// GENERATED by .design-sync/gen-i18n-resources.mjs - do not edit by hand.
//
// Static equivalent of packages/workout-spa-editor/src/i18n/resources.ts for
// the design-sync bundle. The original discovers catalogs with Vite's
// `import.meta.glob`, which esbuild cannot provide; the exported surface here
// is identical, so the components render the same strings the storybook
// reference renders.

import type { Locale, LocaleNamespaces } from "@kaiord/i18n";

import en_athlete from "../packages/workout-spa-editor/src/i18n/locales/en/athlete.json";
import en_calendar from "../packages/workout-spa-editor/src/i18n/locales/en/calendar.json";
import en_chat from "../packages/workout-spa-editor/src/i18n/locales/en/chat.json";
import en_coach from "../packages/workout-spa-editor/src/i18n/locales/en/coach.json";
import en_coaching from "../packages/workout-spa-editor/src/i18n/locales/en/coaching.json";
import en_common from "../packages/workout-spa-editor/src/i18n/locales/en/common.json";
import en_connections from "../packages/workout-spa-editor/src/i18n/locales/en/connections.json";
import en_create_workout from "../packages/workout-spa-editor/src/i18n/locales/en/create-workout.json";
import en_daily from "../packages/workout-spa-editor/src/i18n/locales/en/daily.json";
import en_editor from "../packages/workout-spa-editor/src/i18n/locales/en/editor.json";
import en_errors from "../packages/workout-spa-editor/src/i18n/locales/en/errors.json";
import en_health from "../packages/workout-spa-editor/src/i18n/locales/en/health.json";
import en_help from "../packages/workout-spa-editor/src/i18n/locales/en/help.json";
import en_import from "../packages/workout-spa-editor/src/i18n/locales/en/import.json";
import en_labImport from "../packages/workout-spa-editor/src/i18n/locales/en/labImport.json";
import en_labs from "../packages/workout-spa-editor/src/i18n/locales/en/labs.json";
import en_labs_ui from "../packages/workout-spa-editor/src/i18n/locales/en/labs-ui.json";
import en_library from "../packages/workout-spa-editor/src/i18n/locales/en/library.json";
import en_nav from "../packages/workout-spa-editor/src/i18n/locales/en/nav.json";
import en_nutrition from "../packages/workout-spa-editor/src/i18n/locales/en/nutrition.json";
import en_palette from "../packages/workout-spa-editor/src/i18n/locales/en/palette.json";
import en_settings from "../packages/workout-spa-editor/src/i18n/locales/en/settings.json";
import en_setup from "../packages/workout-spa-editor/src/i18n/locales/en/setup.json";
import en_targets from "../packages/workout-spa-editor/src/i18n/locales/en/targets.json";
import en_workout_detail from "../packages/workout-spa-editor/src/i18n/locales/en/workout-detail.json";
import en_zones from "../packages/workout-spa-editor/src/i18n/locales/en/zones.json";
import es_athlete from "../packages/workout-spa-editor/src/i18n/locales/es/athlete.json";
import es_calendar from "../packages/workout-spa-editor/src/i18n/locales/es/calendar.json";
import es_chat from "../packages/workout-spa-editor/src/i18n/locales/es/chat.json";
import es_coach from "../packages/workout-spa-editor/src/i18n/locales/es/coach.json";
import es_coaching from "../packages/workout-spa-editor/src/i18n/locales/es/coaching.json";
import es_common from "../packages/workout-spa-editor/src/i18n/locales/es/common.json";
import es_connections from "../packages/workout-spa-editor/src/i18n/locales/es/connections.json";
import es_create_workout from "../packages/workout-spa-editor/src/i18n/locales/es/create-workout.json";
import es_daily from "../packages/workout-spa-editor/src/i18n/locales/es/daily.json";
import es_editor from "../packages/workout-spa-editor/src/i18n/locales/es/editor.json";
import es_errors from "../packages/workout-spa-editor/src/i18n/locales/es/errors.json";
import es_health from "../packages/workout-spa-editor/src/i18n/locales/es/health.json";
import es_help from "../packages/workout-spa-editor/src/i18n/locales/es/help.json";
import es_import from "../packages/workout-spa-editor/src/i18n/locales/es/import.json";
import es_labImport from "../packages/workout-spa-editor/src/i18n/locales/es/labImport.json";
import es_labs from "../packages/workout-spa-editor/src/i18n/locales/es/labs.json";
import es_labs_ui from "../packages/workout-spa-editor/src/i18n/locales/es/labs-ui.json";
import es_library from "../packages/workout-spa-editor/src/i18n/locales/es/library.json";
import es_nav from "../packages/workout-spa-editor/src/i18n/locales/es/nav.json";
import es_nutrition from "../packages/workout-spa-editor/src/i18n/locales/es/nutrition.json";
import es_palette from "../packages/workout-spa-editor/src/i18n/locales/es/palette.json";
import es_settings from "../packages/workout-spa-editor/src/i18n/locales/es/settings.json";
import es_setup from "../packages/workout-spa-editor/src/i18n/locales/es/setup.json";
import es_targets from "../packages/workout-spa-editor/src/i18n/locales/es/targets.json";
import es_workout_detail from "../packages/workout-spa-editor/src/i18n/locales/es/workout-detail.json";
import es_zones from "../packages/workout-spa-editor/src/i18n/locales/es/zones.json";

const CATALOGS: Record<string, LocaleNamespaces> = {
  "en": {
    "athlete": en_athlete,
    "calendar": en_calendar,
    "chat": en_chat,
    "coach": en_coach,
    "coaching": en_coaching,
    "common": en_common,
    "connections": en_connections,
    "create-workout": en_create_workout,
    "daily": en_daily,
    "editor": en_editor,
    "errors": en_errors,
    "health": en_health,
    "help": en_help,
    "import": en_import,
    "labImport": en_labImport,
    "labs": en_labs,
    "labs-ui": en_labs_ui,
    "library": en_library,
    "nav": en_nav,
    "nutrition": en_nutrition,
    "palette": en_palette,
    "settings": en_settings,
    "setup": en_setup,
    "targets": en_targets,
    "workout-detail": en_workout_detail,
    "zones": en_zones,
  },
  "es": {
    "athlete": es_athlete,
    "calendar": es_calendar,
    "chat": es_chat,
    "coach": es_coach,
    "coaching": es_coaching,
    "common": es_common,
    "connections": es_connections,
    "create-workout": es_create_workout,
    "daily": es_daily,
    "editor": es_editor,
    "errors": es_errors,
    "health": es_health,
    "help": es_help,
    "import": es_import,
    "labImport": es_labImport,
    "labs": es_labs,
    "labs-ui": es_labs_ui,
    "library": es_library,
    "nav": es_nav,
    "nutrition": es_nutrition,
    "palette": es_palette,
    "settings": es_settings,
    "setup": es_setup,
    "targets": es_targets,
    "workout-detail": es_workout_detail,
    "zones": es_zones,
  },
};

export const DEFAULT_NAMESPACE = "common";

/** The English catalog: i18next's fallback and the default render language. */
export const DEFAULT_CATALOG: LocaleNamespaces = CATALOGS["en"] ?? {};

export const NAMESPACES = Object.keys(DEFAULT_CATALOG);

export const getLocaleNamespaces = (
  locale: Locale
): LocaleNamespaces | undefined => CATALOGS[locale];

/** Every catalog is bundled here, so this resolves without a network round. */
export const loadLocaleNamespaces = async (
  locale: Locale
): Promise<LocaleNamespaces> => CATALOGS[locale] ?? DEFAULT_CATALOG;
