import type { KRD, RepetitionBlock, Workout, WorkoutStep } from "../types/krd";
import { isWorkoutStep } from "../types/krd";
import type { UIWorkout } from "../types/krd-ui";
import { defaultIdProvider, type IdProvider } from "./providers/id-provider";
import { asItemId, type ItemId } from "./providers/item-id";

const hydrateStep = (
  step: WorkoutStep & { id?: string },
  idProvider: IdProvider
): WorkoutStep & { id: ItemId } => ({
  ...step,
  id: step.id ? asItemId(step.id) : idProvider(),
});

const hydrateBlock = (
  block: RepetitionBlock,
  idProvider: IdProvider
): RepetitionBlock & { id: ItemId } => ({
  ...block,
  id: block.id ? asItemId(block.id) : idProvider(),
  steps: block.steps.map((s) => hydrateStep(s, idProvider)),
});

const regenerateItem = (
  item: WorkoutStep | RepetitionBlock,
  idProvider: IdProvider
): WorkoutStep | RepetitionBlock =>
  isWorkoutStep(item)
    ? { ...item, id: idProvider() }
    : {
        ...item,
        id: idProvider(),
        steps: item.steps.map((s) => ({ ...s, id: idProvider() })),
      };

/**
 * Hydrate a portable KRD into an in-memory UIWorkout by ensuring every
 * step and block carries an `ItemId`.
 *
 * By default, existing id-like strings (e.g. block ids generated by
 * legacy code, or ids round-tripped through Dexie) are preserved so
 * consumers that key off block id continue to function during the
 * staged migration. Pass `{ preserveExistingIds: false }` to regenerate
 * every id — used by the paste-path trust boundary to prevent a
 * clipboard-supplied id from redirecting focus onto an existing item.
 */
export const hydrateUIWorkout = (
  krd: KRD,
  options: { idProvider?: IdProvider; preserveExistingIds?: boolean } = {}
): UIWorkout => {
  const idProvider = options.idProvider ?? defaultIdProvider;
  const preserve = options.preserveExistingIds ?? true;
  const workout = krd.extensions?.structured_workout as Workout | undefined;

  if (!workout) return krd;

  const hydrated = workout.steps.map((item) =>
    preserve
      ? isWorkoutStep(item)
        ? hydrateStep(item, idProvider)
        : hydrateBlock(item, idProvider)
      : regenerateItem(item, idProvider)
  );

  return {
    ...krd,
    extensions: {
      ...krd.extensions,
      structured_workout: { ...workout, steps: hydrated },
    },
  };
};

export type { ItemId };
