import type { LucideIcon } from "lucide-react";
import {
  ArrowDown,
  ArrowUp,
  Bell,
  Calendar,
  CalendarCheck,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Flame,
  FlaskConical,
  Heart,
  HelpCircle,
  Info,
  LayoutGrid,
  Link,
  MessageCircle,
  MoreHorizontal,
  Pencil,
  Plus,
  RefreshCw,
  Route,
  Settings,
  Shield,
  Sparkles,
  Target,
  TrendingUp,
  TriangleAlert,
  Upload,
  User,
  Utensils,
  Watch,
  X,
  Zap,
} from "lucide-react";

import { SPORT_ICONS } from "./sport-icons";

/* Stable semantic names used by the redesign surfaces, mapped to concrete
   lucide-react icons. Screens reference icons by these names (via the
   `IconName` type) so the underlying icon set can change in one place
   without touching every call site. Names mirror the design handoff. */
export const ICON_MAP = {
  ...SPORT_ICONS,
  today: CalendarCheck,
  library: LayoutGrid,
  cards: LayoutGrid,
  plus: Plus,
  athlete: User,
  gear: Settings,
  zap: Zap,
  sparkle: Sparkles,
  heart: Heart,
  watch: Watch,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  chevR: ChevronRight,
  chevL: ChevronLeft,
  chevD: ChevronDown,
  check: Check,
  info: Info,
  x: X,
  clock: Clock,
  route: Route,
  flame: Flame,
  sync: RefreshCw,
  link: Link,
  dots: MoreHorizontal,
  edit: Pencil,
  target: Target,
  shield: Shield,
  calendar: Calendar,
  bell: Bell,
  trend: TrendingUp,
  upload: Upload,
  nutrition: Utensils,
  chat: MessageCircle,
  labs: FlaskConical,
  help: HelpCircle,
  /* The palette has no warning hue — amber is Z4. A state that needs the
     user is said with this icon plus a sentence, never with colour. */
  alert: TriangleAlert,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_MAP;
