/**
 * Visual regression specs for the CoachingSidebar component.
 *
 * Covers desktop (1024×768) and mobile (768×1024) viewports for a
 * matched coaching workout. Baselines are generated by the user locally
 * on ubuntu-latest/chromium (or in mcr.microsoft.com/playwright:focal).
 *
 * Closes #554.
 */

import type { Page } from "@playwright/test";
import { expect, test } from "@playwright/test";

import { clearDexie, getWeekDates } from "./helpers/seed-dexie";
import { disableOnboardingTutorial } from "./test-setup";

const PROFILE_ID = "visual-sidebar-profile";
const SOURCE = "train2go";
const SOURCE_ID = "visual-sidebar-activity";
const WORKOUT_ID = "visual-sidebar-workout";

type Db = {
  table: (n: string) => {
    put: (r: unknown) => Promise<unknown>;
  };
};

/**
 * Seeds the minimal Dexie state needed for a matched coaching workout:
 *   - a profile with a linked train2go account
 *   - a coaching activity
 *   - a workout (sourceId matches the composite coachingActivityId)
 *   - a sessionMatch row linking the two
 */
const seedMatchedCoachingWorkout = async (
  page: Page,
  day: string,
  ts: string
) => {
  await page.evaluate(
    async ({ profileId, source, sourceId, workoutId, day, ts }) => {
      const db = (window as unknown as Record<string, unknown>)
        .__KAIORD_DB__ as Db;

      await db.table("profiles").put({
        id: profileId,
        name: "Visual test profile",
        sportZones: {},
        linkedAccounts: [{ source: "train2go", externalId: "t2g-visual-1" }],
        createdAt: ts,
        updatedAt: ts,
      });
      await db.table("meta").put({ key: "activeProfileId", value: profileId });

      // Out-of-week dummy to satisfy FirstVisitState onboarding guard
      await db.table("workouts").put({
        id: "visual-dummy-out-of-week",
        date: "2020-01-01",
        state: "raw",
        sport: "cycling",
        source: "manual",
        sourceId: "visual-dummy",
        planId: null,
        raw: { description: "x", duration: { value: 600, unit: "s" } },
        krd: null,
        lastProcessingError: null,
        feedback: null,
        aiMeta: null,
        garminPushId: null,
        tags: [],
        previousState: null,
        createdAt: ts,
        modifiedAt: null,
        updatedAt: ts,
      });

      const compositeId = `${profileId}:${source}:${sourceId}`;

      await db.table("coachingActivities").put({
        id: compositeId,
        profileId,
        source,
        sourceId,
        date: day,
        sport: "cycling",
        title: "Visual regression test activity",
        status: "pending",
        description:
          "5 min warm-up @ 55% FTP\n3 × 10 min @ 90% FTP / 5 min recovery\n5 min cool-down @ 50% FTP",
        duration: "60 min",
        fetchedAt: ts,
      });

      await db.table("workouts").put({
        id: workoutId,
        profileId,
        date: day,
        state: "raw",
        sport: "cycling",
        source,
        sourceId: compositeId,
        planId: null,
        raw: {
          description:
            "5 min warm-up @ 55% FTP\n3 × 10 min @ 90% FTP / 5 min recovery\n5 min cool-down @ 50% FTP",
          duration: { value: 3600, unit: "s" },
        },
        krd: null,
        lastProcessingError: null,
        feedback: null,
        aiMeta: null,
        garminPushId: null,
        tags: [],
        previousState: null,
        createdAt: ts,
        modifiedAt: null,
        updatedAt: ts,
      });

      await db.table("sessionMatches").put({
        id: `${profileId}:${compositeId}`,
        profileId,
        coachingActivityId: compositeId,
        workoutId,
        matchedAt: ts,
        source: "manual",
      });
    },
    {
      profileId: PROFILE_ID,
      source: SOURCE,
      sourceId: SOURCE_ID,
      workoutId: WORKOUT_ID,
      day,
      ts,
    }
  );
};

test.describe("CoachingSidebar visual regression", () => {
  test.beforeEach(async ({ page }) => {
    await disableOnboardingTutorial(page);
  });

  test("should match desktop screenshot at 1024px viewport for matched coaching workout", async ({
    page,
  }) => {
    // Arrange
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.goto("/calendar");
    await page.waitForFunction(
      () =>
        Boolean((window as unknown as Record<string, unknown>).__KAIORD_DB__),
      { timeout: 10_000 }
    );
    await clearDexie(page);
    const day = getWeekDates(0)[2];
    const ts = new Date(day + "T08:00:00Z").toISOString();
    await seedMatchedCoachingWorkout(page, day, ts);

    // Act — workout + sessionMatch are pre-seeded, so navigate straight
    // to the editor. The dialog flow ("Edit manually") only applies to
    // the no-workout state; a pre-matched workout opens directly.
    await page.goto(`/workout/${WORKOUT_ID}`);
    await expect(page.getByTestId("coaching-sidebar")).toBeVisible({
      timeout: 10_000,
    });

    // Assert
    await expect(page).toHaveScreenshot("coaching-sidebar-desktop.png");
  });

  test("should match mobile screenshot at 768px viewport for matched coaching workout", async ({
    page,
  }) => {
    // Arrange
    await page.setViewportSize({ width: 768, height: 1024 });
    await page.goto("/calendar");
    await page.waitForFunction(
      () =>
        Boolean((window as unknown as Record<string, unknown>).__KAIORD_DB__),
      { timeout: 10_000 }
    );
    await clearDexie(page);
    const day = getWeekDates(0)[2];
    const ts = new Date(day + "T08:00:00Z").toISOString();
    await seedMatchedCoachingWorkout(page, day, ts);

    // Act — workout + sessionMatch are pre-seeded, so navigate straight
    // to the editor. The dialog flow ("Edit manually") only applies to
    // the no-workout state; a pre-matched workout opens directly.
    await page.goto(`/workout/${WORKOUT_ID}`);
    await expect(page.getByTestId("coaching-sidebar")).toBeVisible({
      timeout: 10_000,
    });

    // Assert
    await expect(page).toHaveScreenshot("coaching-sidebar-mobile.png");
  });
});
