/**
 * Clinical abbreviations for lab parameters — language-neutral, identical
 * across locales (see the i18n `labs` namespace for localized names).
 */
export const LAB_ABBREVIATIONS: Record<string, string> = {
  rbc: "RBC",
  hemoglobin: "Hb",
  hematocrit: "Hct",
  mcv: "MCV",
  mch: "MCH",
  mchc: "MCHC",
  rdw: "RDW",
  wbc: "WBC",
  platelets: "PLT",
  mpv: "MPV",
  neutrophils_pct: "NEU%",
  neutrophils_abs: "NEU#",
  lymphocytes_pct: "LYM%",
  lymphocytes_abs: "LYM#",
  monocytes_pct: "MON%",
  monocytes_abs: "MON#",
  eosinophils_pct: "EOS%",
  eosinophils_abs: "EOS#",
  basophils_pct: "BAS%",
  basophils_abs: "BAS#",
  glucose: "GLU",
  hba1c: "HbA1c",
  creatinine: "CREA",
  urea: "UREA",
  uric_acid: "URIC",
  egfr: "eGFR",
  cholesterol_total: "TC",
  ldl: "LDL",
  hdl: "HDL",
  triglycerides: "TG",
  non_hdl: "non-HDL",
  apob: "ApoB",
  ast: "AST",
  alt: "ALT",
  ggt: "GGT",
  alp: "ALP",
  bilirubin_total: "TBIL",
  bilirubin_direct: "DBIL",
  sodium: "Na",
  potassium: "K",
  calcium: "Ca",
  magnesium: "Mg",
  phosphorus: "P",
  iron: "Fe",
  ferritin: "FERR",
  transferrin: "TRF",
  tsat: "TSAT",
  tsh: "TSH",
  free_t4: "FT4",
  vitamin_d: "25-OH-D",
  vitamin_b12: "B12",
  folate: "FOL",
  testosterone: "TESTO",
  cortisol: "CORT",
  ck: "CK",
  hs_crp: "hs-CRP",
};
