export { convertLengthToMeters } from "./converters/length-unit.converter";
export { createWorkoutKRD } from "./converters/workout-to-krd.converter";
export { canonicalHash } from "./hash/canonical-hash";
export { deriveExternalId } from "./ingest/derive-external-id";
export type {
  BridgeId,
  HashProjection,
  ManagedDataRegistryEntry,
  ManagedDataType,
} from "./managed-data-type";
export { MANAGED_DATA_REGISTRY, managedDataTypes } from "./managed-data-type";
export type {
  Activity,
  ActivitySummary,
  BodyComposition,
  CadenceValue,
  DailyWellness,
  DayEnergyBalance,
  Duration,
  DurationType,
  EnergyGoal,
  Equipment,
  ExpenditureSource,
  FileType,
  GoalType,
  HealthExtensionPayload,
  HealthFileType,
  HeartRateValue,
  HrvSummary,
  Intensity,
  KRD,
  KRDEvent,
  KRDExtensions,
  KRDLap,
  KRDLapTrigger,
  KRDMetadata,
  KRDRecord,
  KRDSession,
  LengthUnit,
  MacroNutrients,
  MealSlot,
  PaceValue,
  PlannedSession,
  PlannedSessionStatus,
  PowerValue,
  RepetitionBlock,
  SleepRecord,
  SleepStage,
  Sport,
  SportCategory,
  StressEpisode,
  StrokeTypeValue,
  SubSport,
  SwimStroke,
  Target,
  TargetType,
  TargetUnit,
  TrainingZoneBand,
  TrainingZones,
  TrainingZoneSet,
  WeightMeasurement,
  Workout,
  WorkoutStep,
} from "./schemas";
export {
  activitySchema,
  activitySummarySchema,
  BODY_FAT_TOLERANCE_PERCENT,
  bodyCompositionSchema,
  DAILY_KCAL_TOLERANCE,
  DAILY_STEPS_TOLERANCE,
  dailyWellnessSchema,
  dayEnergyBalanceSchema,
  durationSchema,
  durationTypeSchema,
  energyGoalSchema,
  equipmentSchema,
  expenditureSourceSchema,
  fileTypeSchema,
  FIT_TO_SWIM_STROKE,
  goalTypeSchema,
  healthExtensionPayloadSchema,
  healthFileTypes,
  HRV_TOLERANCE_MS,
  hrvSummarySchema,
  intensitySchema,
  isHealthFileType,
  krdEventSchema,
  krdExtensionsSchema,
  krdLapSchema,
  krdLapTriggerSchema,
  krdMetadataSchema,
  krdRecordSchema,
  krdSchema,
  krdSessionSchema,
  lengthUnitSchema,
  macroNutrientsSchema,
  mealSlotSchema,
  plannedSessionSchema,
  plannedSessionStatusSchema,
  repetitionBlockSchema,
  SLEEP_STAGE_TOLERANCE_SECONDS,
  SLEEP_TOTAL_DURATION_TOLERANCE_SECONDS,
  sleepRecordSchema,
  sleepStageSchema,
  sportCategory,
  sportSchema,
  STRESS_TOLERANCE,
  stressEpisodeSchema,
  subSportSchema,
  SWIM_STROKE_TO_FIT,
  swimStrokeSchema,
  targetSchema,
  targetTypeSchema,
  targetUnitSchema,
  trainingZoneBandSchema,
  trainingZoneSetSchema,
  trainingZonesSchema,
  WEIGHT_TOLERANCE_KG,
  weightMeasurementSchema,
  workoutLikeFileTypes,
  workoutSchema,
  workoutStepSchema,
} from "./schemas";
export { isRepetitionBlock } from "./type-guards";
export type { ToleranceViolation, ValidationError } from "./types/errors";
export {
  createFitParsingError,
  createGarminParsingError,
  createKrdValidationError,
  createServiceApiError,
  createServiceAuthError,
  createTcxParsingError,
  createTcxValidationError,
  createUnsupportedKrdTypeError,
  createZwiftParsingError,
  createZwiftValidationError,
  FitParsingError,
  GarminParsingError,
  KrdValidationError,
  ServiceApiError,
  ServiceAuthError,
  TcxParsingError,
  TcxValidationError,
  ToleranceExceededError,
  UnsupportedKrdTypeError,
  ZwiftParsingError,
  ZwiftValidationError,
} from "./types/errors";
export type {
  SchemaValidator,
  ToleranceChecker,
  ToleranceConfig,
} from "./validation";
export {
  createSchemaValidator,
  createToleranceChecker,
  DEFAULT_TOLERANCES,
  extractWorkout,
  toleranceConfigSchema,
  toleranceViolationSchema,
  validateKrd,
} from "./validation";
export type { PowerZone } from "./zones";
export {
  isPowerZone,
  percentFtpToZone,
  POWER_ZONE_PERCENT_FTP,
  POWER_ZONES,
  zoneToPercentFtp,
} from "./zones";
