export { convertLengthToMeters } from "./converters/length-unit.converter";
export { createWorkoutKRD } from "./converters/workout-to-krd.converter";
export type {
  BodyComposition,
  CadenceValue,
  DailyWellness,
  Duration,
  DurationType,
  Equipment,
  FileType,
  HealthExtensionPayload,
  HealthFileType,
  HeartRateValue,
  HrvSummary,
  Intensity,
  KRD,
  KRDEvent,
  KRDExtensions,
  KRDLap,
  KRDLapTrigger,
  KRDMetadata,
  KRDRecord,
  KRDSession,
  LengthUnit,
  PaceValue,
  PowerValue,
  RepetitionBlock,
  SleepRecord,
  SleepStage,
  Sport,
  StressEpisode,
  StrokeTypeValue,
  SubSport,
  SwimStroke,
  Target,
  TargetType,
  TargetUnit,
  WeightMeasurement,
  Workout,
  WorkoutStep,
} from "./schemas";
export {
  BODY_FAT_TOLERANCE_PERCENT,
  bodyCompositionSchema,
  DAILY_KCAL_TOLERANCE,
  DAILY_STEPS_TOLERANCE,
  dailyWellnessSchema,
  durationSchema,
  durationTypeSchema,
  equipmentSchema,
  fileTypeSchema,
  FIT_TO_SWIM_STROKE,
  healthExtensionPayloadSchema,
  healthFileTypes,
  HRV_TOLERANCE_MS,
  hrvSummarySchema,
  intensitySchema,
  isHealthFileType,
  krdEventSchema,
  krdExtensionsSchema,
  krdLapSchema,
  krdLapTriggerSchema,
  krdMetadataSchema,
  krdRecordSchema,
  krdSchema,
  krdSessionSchema,
  lengthUnitSchema,
  repetitionBlockSchema,
  SLEEP_STAGE_TOLERANCE_SECONDS,
  SLEEP_TOTAL_DURATION_TOLERANCE_SECONDS,
  sleepRecordSchema,
  sleepStageSchema,
  sportSchema,
  STRESS_TOLERANCE,
  stressEpisodeSchema,
  subSportSchema,
  SWIM_STROKE_TO_FIT,
  swimStrokeSchema,
  targetSchema,
  targetTypeSchema,
  targetUnitSchema,
  WEIGHT_TOLERANCE_KG,
  weightMeasurementSchema,
  workoutLikeFileTypes,
  workoutSchema,
  workoutStepSchema,
} from "./schemas";
export { isRepetitionBlock } from "./type-guards";
export type { ToleranceViolation, ValidationError } from "./types/errors";
export {
  createFitParsingError,
  createGarminParsingError,
  createKrdValidationError,
  createServiceApiError,
  createServiceAuthError,
  createTcxParsingError,
  createTcxValidationError,
  createToleranceExceededError,
  createUnsupportedKrdTypeError,
  createZwiftParsingError,
  createZwiftValidationError,
  FitParsingError,
  GarminParsingError,
  KrdValidationError,
  ServiceApiError,
  ServiceAuthError,
  TcxParsingError,
  TcxValidationError,
  ToleranceExceededError,
  UnsupportedKrdTypeError,
  ZwiftParsingError,
  ZwiftValidationError,
} from "./types/errors";
export type {
  SchemaValidator,
  ToleranceChecker,
  ToleranceConfig,
} from "./validation";
export {
  createSchemaValidator,
  createToleranceChecker,
  DEFAULT_TOLERANCES,
  extractWorkout,
  toleranceConfigSchema,
  toleranceViolationSchema,
  validateKrd,
} from "./validation";
export type { PowerZone } from "./zones";
export {
  isPowerZone,
  percentFtpToZone,
  POWER_ZONE_PERCENT_FTP,
  POWER_ZONES,
  zoneToPercentFtp,
} from "./zones";
