export {
  durationSchema,
  durationTypeSchema,
  equipmentSchema,
  FIT_TO_SWIM_STROKE,
  fileTypeSchema,
  intensitySchema,
  krdEventSchema,
  krdLapSchema,
  krdLapTriggerSchema,
  krdMetadataSchema,
  krdRecordSchema,
  krdSchema,
  krdSessionSchema,
  lengthUnitSchema,
  repetitionBlockSchema,
  sportSchema,
  subSportSchema,
  SWIM_STROKE_TO_FIT,
  swimStrokeSchema,
  targetSchema,
  targetTypeSchema,
  targetUnitSchema,
  workoutSchema,
  workoutStepSchema,
} from "./schemas";
export type {
  CadenceValue,
  Duration,
  DurationType,
  Equipment,
  FileType,
  HeartRateValue,
  Intensity,
  KRD,
  KRDEvent,
  KRDLap,
  KRDLapTrigger,
  KRDMetadata,
  KRDRecord,
  KRDSession,
  LengthUnit,
  PaceValue,
  PowerValue,
  RepetitionBlock,
  Sport,
  StrokeTypeValue,
  SubSport,
  SwimStroke,
  Target,
  TargetType,
  TargetUnit,
  Workout,
  WorkoutStep,
} from "./schemas";
export { isRepetitionBlock } from "./type-guards";
export { convertLengthToMeters } from "./converters/length-unit.converter";
export { createWorkoutKRD } from "./converters/workout-to-krd.converter";
export {
  FitParsingError,
  GarminParsingError,
  KrdValidationError,
  ServiceApiError,
  ServiceAuthError,
  TcxParsingError,
  TcxValidationError,
  ToleranceExceededError,
  ZwiftParsingError,
  ZwiftValidationError,
  createFitParsingError,
  createGarminParsingError,
  createKrdValidationError,
  createServiceApiError,
  createServiceAuthError,
  createTcxParsingError,
  createTcxValidationError,
  createToleranceExceededError,
  createZwiftParsingError,
  createZwiftValidationError,
} from "./types/errors";
export type { ToleranceViolation, ValidationError } from "./types/errors";
export {
  DEFAULT_TOLERANCES,
  createSchemaValidator,
  createToleranceChecker,
  extractWorkout,
  toleranceConfigSchema,
  toleranceViolationSchema,
  validateKrd,
} from "./validation";
export type {
  SchemaValidator,
  ToleranceChecker,
  ToleranceConfig,
} from "./validation";
